# Generated by Django 4.0.5 on 2022-06-24 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lide', '0002_initial'),
        ('zavody', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodoveHodnoceni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, verbose_name='Název')),
                ('hodnoceni', models.TextField(help_text='formát:<br>1-50<i>(enter)</i><br>2-47<br>3-44', verbose_name='Hodnocení prvních pozic')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Informace')),
            ],
            options={
                'verbose_name': 'Bodové hodnocení pozic',
                'verbose_name_plural': 'Bodová hodnocení pozic',
            },
        ),
        migrations.CreateModel(
            name='Pohar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, verbose_name='Název')),
                ('datum', models.DateField(verbose_name='Datum pořádání')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info')),
                ('zavodu', models.SmallIntegerField(blank=True, help_text='počet nejlepších závodů jež budou započítany,<br>        při prázdné kolonce budou použity všechny závody', null=True, verbose_name='Počet nejlepších výsledků')),
                ('bod_hodnoceni', models.ForeignKey(blank=True, help_text='bodová tabulka pro pohár,<br>        bude použita v případě nespecifikované tabulky u kategorie,<br>        v případě prázdného kolonky se boduje postupně odzadu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pohary', to='pohary.bodovehodnoceni', verbose_name='Bodové hodnocení')),
                ('rocniky', models.ManyToManyField(related_name='pohary', to='zavody.rocnik', verbose_name='Ročníky')),
            ],
            options={
                'verbose_name': 'Pohár',
                'verbose_name_plural': 'Poháry',
                'ordering': ('-datum',),
                'unique_together': {('nazev', 'datum')},
            },
        ),
        migrations.CreateModel(
            name='KategoriePoharu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, verbose_name='Název')),
                ('znacka', models.CharField(blank=True, help_text='značka kategorie se použije při        porovnávání s <b>vnucenými kategoriemi</b> závodníků', max_length=10, null=True, verbose_name='Značka')),
                ('pohlavi', models.CharField(blank=True, choices=[('m', 'muži'), ('z', 'ženy')], max_length=1, null=True, verbose_name='Pohlaví')),
                ('vek_od', models.SmallIntegerField(blank=True, help_text='věk závodníka včetně', null=True, verbose_name='Věk od')),
                ('vek_do', models.SmallIntegerField(blank=True, help_text='věk závodníka včetně', null=True, verbose_name='Věk do')),
                ('poradi', models.SmallIntegerField(blank=True, null=True, verbose_name='Pořadí')),
                ('zavodu', models.SmallIntegerField(blank=True, help_text='počet nejlepších závodů jež budou započítany,        <br>při prázdné kolonce bude použita hodnota poháru', null=True, verbose_name='Počet nejlepších výsledků')),
                ('atributy', models.ManyToManyField(blank=True, to='lide.atribut', verbose_name='Požadované atributy člověka')),
                ('bod_hodnoceni', models.ForeignKey(blank=True, help_text='bodová tabulka pro kategorii poháru,<br>        při prázdné kolonce bude použita tabulka z poháru', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategorie', to='pohary.bodovehodnoceni', verbose_name='Bodové hodnocení')),
                ('pohar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategorie_poharu', to='pohary.pohar', verbose_name='pohár')),
            ],
            options={
                'verbose_name': 'Kategorie poháru',
                'verbose_name_plural': 'Kategorie pohárů',
                'ordering': ('poradi', 'id'),
                'unique_together': {('pohar', 'nazev')},
            },
        ),
    ]
