# Generated by Django 4.0.5 on 2025-01-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zavody', '0002_remove_kategorie_atributy'),
        ('pohary', '0003_pohar_kluby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoriepoharu',
            name='bod_hodnoceni',
            field=models.ForeignKey(blank=True, help_text='bodová tabulka pro kategorii poháru,<br>při prázdné kolonce bude použita tabulka z poháru', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategorie', to='pohary.bodovehodnoceni', verbose_name='Bodové hodnocení'),
        ),
        migrations.AlterField(
            model_name='kategoriepoharu',
            name='zavodu',
            field=models.SmallIntegerField(blank=True, help_text='počet nejlepších závodů jež budou započítany,<br>při prázdné kolonce bude použita hodnota poháru', null=True, verbose_name='Počet nejlepších výsledků'),
        ),
        migrations.AlterField(
            model_name='kategoriepoharu',
            name='znacka',
            field=models.CharField(blank=True, help_text='značka kategorie se použije při porovnávání s <b>vnucenými kategoriemi</b> závodníků', max_length=10, null=True, verbose_name='Značka'),
        ),
        migrations.AlterField(
            model_name='pohar',
            name='bod_hodnoceni',
            field=models.ForeignKey(blank=True, help_text='bodová tabulka pro pohár,<br>bude použita v případě nespecifikované tabulky u kategorie,<br>v případě prázdného kolonky se boduje postupně odzadu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pohary', to='pohary.bodovehodnoceni', verbose_name='Bodové hodnocení'),
        ),
        migrations.AlterField(
            model_name='pohar',
            name='zavodu',
            field=models.SmallIntegerField(blank=True, help_text='defaultní počet nejlepších závodů pro všechny sporty jež budou započítany,<br> při prázdné kolonce budou použity všechny závody', null=True, verbose_name='Počet nejlepších výsledků'),
        ),
        migrations.CreateModel(
            name='PocetZavoduPoharuSportu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zavodu', models.PositiveSmallIntegerField(blank=True, help_text='defaultní počet nejlepších závodů pro všechny sporty jež budou započítany,<br> při prázdné kolonce budou použity všechny závody', null=True, verbose_name='Počet nejlepších výsledků')),
                ('pohar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocet_zavodu_sportu', to='pohary.pohar', verbose_name='Pohár')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocet_zavodu_poharu', to='zavody.sport', verbose_name='Sport')),
            ],
            options={
                'verbose_name': 'Počet závodů pro sport',
                'verbose_name_plural': 'Počty závodů pro sport',
                'unique_together': {('pohar', 'sport')},
            },
        ),
    ]
