# Generated by Django 4.0.5 on 2025-02-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pohary', '0004_alter_kategoriepoharu_bod_hodnoceni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pohar',
            name='ignorovat_kategorie_zavodnika',
            field=models.BooleanField(default=False, help_text='pokud je povoleno, pak při filtrování závodníku do kategorií není přihlíženo k jejich kategoriím', verbose_name='Ignorovat kategorie závodníků'),
        ),
        migrations.AlterField(
            model_name='bodovehodnoceni',
            name='hodnoceni',
            field=models.TextField(help_text='formát: 1-50<i>(enter)</i> 2-47 3-44', verbose_name='Hodnocení prvních pozic'),
        ),
        migrations.AlterField(
            model_name='kategoriepoharu',
            name='bod_hodnoceni',
            field=models.ForeignKey(blank=True, help_text='bodová tabulka pro kategorii poháru, při prázdné kolonce bude použita tabulka z poháru', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategorie', to='pohary.bodovehodnoceni', verbose_name='Bodové hodnocení'),
        ),
        migrations.AlterField(
            model_name='kategoriepoharu',
            name='zavodu',
            field=models.SmallIntegerField(blank=True, help_text='počet nejlepších závodů jež budou započítany, při prázdné kolonce bude použita hodnota poháru', null=True, verbose_name='Počet nejlepších výsledků'),
        ),
        migrations.AlterField(
            model_name='kategoriepoharu',
            name='znacka',
            field=models.CharField(blank=True, help_text='značka kategorie se použije při porovnávání s vnucenými kategoriemi závodníků', max_length=10, null=True, verbose_name='Značka'),
        ),
        migrations.AlterField(
            model_name='pocetzavodupoharusportu',
            name='zavodu',
            field=models.PositiveSmallIntegerField(blank=True, help_text='počet nejlepších výsledků konkrétního sportu jež budou do poháru započítany, při prázdné kolonce budou použity všechny závody', null=True, verbose_name='Počet nejlepších výsledků konkrétního sportu'),
        ),
        migrations.AlterField(
            model_name='pohar',
            name='bod_hodnoceni',
            field=models.ForeignKey(blank=True, help_text='bodová tabulka pro pohár, bude použita v případě nespecifikované tabulky u kategorie, v případě prázdného kolonky se boduje postupně odzadu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pohary', to='pohary.bodovehodnoceni', verbose_name='Bodové hodnocení'),
        ),
        migrations.AlterField(
            model_name='pohar',
            name='zavodu',
            field=models.SmallIntegerField(blank=True, help_text='defaultní počet nejlepších výsledků pro všechny sporty jež budou do poháru započítany, při prázdné kolonce budou použity všechny závody', null=True, verbose_name='Počet nejlepších výsledků všech sportů'),
        ),
    ]
