# Generated by Django 4.0.5 on 2026-08-31 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lide', '0003_remove_clovek_atributy_delete_atribut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Název')),
                ('zkratka', models.SlugField(blank=True, unique=True)),
                ('poradi', models.PositiveSmallIntegerField(default=100, help_text='určuje pořadí států v nabídkách', verbose_name='Pořadí')),
            ],
            options={
                'verbose_name': 'Stát',
                'verbose_name_plural': 'Státy',
                'ordering': ('poradi', 'zkratka', 'nazev'),
            },
        ),
        migrations.AddField(
            model_name='clovek',
            name='stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lidi', to='lide.stat', verbose_name='Stát'),
        ),
    ]
