# Generated by Django 4.0.5 on 2022-06-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, unique=True, verbose_name='Název')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('nazev_slug_sorting', models.SlugField(editable=False)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info')),
            ],
            options={
                'verbose_name': 'Klub',
                'verbose_name_plural': 'Kluby',
                'ordering': ('nazev_slug_sorting',),
            },
        ),
    ]
