# Generated by Django 4.0.5 on 2022-06-24 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kluby', '0001_initial'),
        ('zavody', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klub',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kluby', to='zavody.sport', verbose_name='sport'),
        ),
    ]
