# Generated by Django 4.0.5 on 2024-10-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluby', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klub',
            name='klub_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Klubové ID'),
        ),
        migrations.AddField(
            model_name='klub',
            name='zkratka',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Zkratka'),
        ),
    ]
