# Generated by Django 4.0.5 on 2022-06-24 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, unique=True, verbose_name='Název')),
                ('slug', models.SlugField(editable=False)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info')),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sporty',
            },
        ),
        migrations.CreateModel(
            name='Zavod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, unique=True, verbose_name='Název')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('korekce_sezony', models.BooleanField(default=False, help_text='zatrhni u podzimních lyžařských běhů pro použití kategorií zimní sezóny', verbose_name='Korekce sezóny')),
                ('misto', models.CharField(blank=True, max_length=120, null=True, verbose_name='Místo')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zavody', to='zavody.sport', verbose_name='sport')),
            ],
            options={
                'verbose_name': 'Závod',
                'verbose_name_plural': 'Závody',
                'ordering': ('-rocniky__datum', 'sport', 'nazev'),
            },
        ),
        migrations.CreateModel(
            name='Rocnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(blank=True, help_text='pokud není název vyplněn, pak se dědí z rodičovského závodu', max_length=50, null=True, verbose_name='Název')),
                ('datum', models.DateField(verbose_name='Datum pořádání')),
                ('cas', models.TimeField(blank=True, null=True, verbose_name='Čas')),
                ('misto', models.CharField(blank=True, help_text='pokud není místo vyplněno, pak se dědí z rodičovského závodu', max_length=120, null=True, verbose_name='Místo konání')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info')),
                ('zavod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rocniky', to='zavody.zavod', verbose_name='závod')),
            ],
            options={
                'verbose_name': 'Ročník závodu',
                'verbose_name_plural': 'Ročníky zavodů',
                'ordering': ('-datum',),
                'unique_together': {('zavod', 'datum')},
            },
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, verbose_name='Název')),
                ('znacka', models.CharField(blank=True, help_text='značka kategorie se použije při        porovnávání s vnucenými kategoriemi závodníků <b>u kategorií pohárů</b>', max_length=10, null=True, verbose_name='Značka')),
                ('pohlavi', models.CharField(blank=True, choices=[('m', 'muži'), ('z', 'ženy')], max_length=1, null=True, verbose_name='Pohlaví')),
                ('vek_od', models.SmallIntegerField(blank=True, help_text='věk závodníka včetně, pokud není vyplněn bere se jako 0', null=True, verbose_name='Věk od')),
                ('vek_do', models.SmallIntegerField(blank=True, help_text='věk závodníka včetně, pokud není vyplněn bere se jako neomezený! (nepsat zbytečně 100 atd.)', null=True, verbose_name='Věk do')),
                ('delka_trate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Délka tratě')),
                ('poradi', models.SmallIntegerField(blank=True, null=True, verbose_name='Pořadí')),
                ('spusteni_stopek', models.TimeField(blank=True, help_text='středoevropský čas, kdy byli pro kategorii spuštěny stopky', null=True, verbose_name='Čas spuštění stopek kategorie')),
                ('startovne', models.SmallIntegerField(blank=True, null=True, verbose_name='Startovné')),
                ('atributy', models.ManyToManyField(blank=True, to='lide.atribut', verbose_name='Požadované atributy člověka')),
                ('rocnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategorie', to='zavody.rocnik', verbose_name='ročník')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
                'ordering': ('poradi', 'id'),
                'unique_together': {('rocnik', 'nazev')},
            },
        ),
    ]
