"""
Django settings for Hanes project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys

RUNSERVER = (len(sys.argv) > 1 and sys.argv[1] == 'runserver')

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ID = 1  # kvuli flatpages

TEMPLATE_DEBUG = False

if RUNSERVER:
    DEBUG = True
    STATIC_URL = '/static/'
    INTERNAL_IPS = '127.0.0.1'
else:
    DEBUG = False
    STATIC_URL = '/static/'  # 'http://localhost:8001/static/'
    FORCE_SCRIPT_NAME = ''  # zruseni pridavani predpony v url 'mysite.fcgi'
    TEMPLATE_DEBUG = False

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*y9vh2hg9-t((rq+nt1w+fv-x#qa=(ni1r!4=4@849m2'

# SECURITY WARNING: don't run with debug turned on in production!
print 'runserver:', RUNSERVER, '| debug:', DEBUG

ALLOWED_HOSTS = ['localhost', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',  # kvuli flatpages
    'django.contrib.flatpages',
    'plugins.django_wysiwyg',

    'hanes',
    'lide',
    'kluby',
    'zavody',
    'zavodnici',
    'pohary'
]

MIDDLEWARE_CLASSES = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    'hanes.middleware.ExceptionLoggingMiddleware'
]

ROOT_URLCONF = 'hanes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hanes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sql'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'cs'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True
NUMBER_GROUPING = 3
THOUSAND_SEPARATOR = ' '
DECIMAL_SEPARATOR = ','
USE_THOUSAND_SEPARATOR = True
DATE_FORMAT = 'd.m.y'
DATETIME_FORMAT = 'd.m.Y - H:i'
SHORT_DATE_FORMAT = 'Y-m-d'
TIME_FORMAT = 'H:i:s,u'
TIME_INPUT_FORMATS = (
    '%H:%M:%S,%f',
    '%H.%M.%S,%f',
    '%H-%M-%S,%f',
    '%H:%M:%S',
    '%H.%M.%S',
    '%H-%M-%S')


USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

if TEMPLATE_DEBUG:
    INSTALLED_APPS.append('debug_toolbar')
    MIDDLEWARE_CLASSES.append('debug_toolbar.middleware.DebugToolbarMiddleware')
